-- ====================================================================
-- Aura Finance - Development Database Reset Script
-- File: supabase/reset_database.sql
-- ====================================================================
-- Purpose: Safely purges all user accounts, transactions, profiles, 
--          settings, and audit logs. Preserves the underlying database 
--          schema, migrations, RLS policies, custom trigger functions,
--          and system default categories.
-- ====================================================================

BEGIN;

-- 1. Purge dependent transactional data in order of foreign key dependencies
DELETE FROM public.goal_transactions;
DELETE FROM public.savings_goals;

-- 2. Purge transactional records that trigger audit logging
DELETE FROM public.incomes;
DELETE FROM public.expenses;
DELETE FROM public.budgets;

-- 3. Purge general configurations and logs
DELETE FROM public.bill_reminders;
DELETE FROM public.system_notifications;
DELETE FROM public.chat_messages;
DELETE FROM public.profiles;
DELETE FROM public.user_settings;

-- 4. Purge custom user-created categories (preserve system default categories where user_id IS NULL)
DELETE FROM public.categories WHERE user_id IS NOT NULL;

-- 5. Clear all audit log history (including logs generated by the triggers during steps 2 and 3)
DELETE FROM public.audit_logs;

-- 6. Purge all authenticated users from GoTrue auth schema
DELETE FROM auth.users;

COMMIT;
