import { ReportDocument } from './ReportModels';
import { ReportExporter } from './ReportExporter';

export class CSVExporter implements ReportExporter {
  export(document: ReportDocument): Blob {
    let csvContent = '';

    // Write header metadata block
    csvContent += `Report Title,${this.escapeCSV(document.title)}\n`;
    csvContent += `Report ID,${document.id}\n`;
    csvContent += `Generated At,${document.metadata.generatedAt}\n`;
    csvContent += `Generated By,${document.metadata.generatedBy}\n`;
    csvContent += `Integrity Hash,${document.metadata.integrityHash}\n\n`;

    // Section 1: KPIs
    csvContent += `FINANCIAL KEY PERFORMANCE INDICATORS (KPIs)\n`;
    csvContent += `Metric,Value\n`;
    csvContent += `Total Income,${document.kpis.totalIncome}\n`;
    csvContent += `Total Expenses,${document.kpis.totalExpenses}\n`;
    csvContent += `Net Surplus,${document.kpis.netBalance}\n`;
    csvContent += `Savings Rate,${document.kpis.savingsRate}%\n`;
    csvContent += `Financial Health Score,${document.kpis.healthScore}/100\n`;
    csvContent += `Emergency Fund Runway,${document.kpis.runway} months\n\n`;

    // Section 2: Detailed Sections
    for (const section of document.sections) {
      csvContent += `${section.title.toUpperCase()}\n`;
      csvContent += `${this.escapeCSV(section.summary)}\n`;

      if (section.id === 'cashflow' && section.charts && section.charts[0]) {
        csvContent += `Month,Inflow,Outflow,Net\n`;
        const trendData = Array.isArray(section.charts[0].data) ? section.charts[0].data : [];
        for (const row of trendData) {
          csvContent += `${row.month || ''},${row.income || 0},${row.expense || 0},${row.net || 0}\n`;
        }
      } else if (section.id === 'budgets' && section.charts && section.charts[0]) {
        csvContent += `Category,Spent,Limit,Utilization %\n`;
        const budgetData = Array.isArray(section.charts[0].data) ? section.charts[0].data : [];
        for (const row of budgetData) {
          csvContent += `${this.escapeCSV(row.name || '')},${row.spent || 0},${row.limit || 0},${row.pct || 0}%\n`;
        }
      } else if (section.id === 'goals' && section.charts && section.charts[0]) {
        csvContent += `Goal,Current,Target,Completion %\n`;
        const goalData = Array.isArray(section.charts[0].data) ? section.charts[0].data : [];
        for (const row of goalData) {
          csvContent += `${this.escapeCSV(row.name || '')},${row.current || 0},${row.target || 0},${row.pct || 0}%\n`;
        }
      } else {
        // Plain key-value rows
        const sectionData = section.data || {};
        for (const [key, value] of Object.entries(sectionData)) {
          csvContent += `${this.escapeCSV(key)},${this.escapeCSV(String(value))}\n`;
        }
      }
      csvContent += `\n`;
    }

    return new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  }

  private escapeCSV(val: string): string {
    if (!val) return '';
    const clean = val.replace(/"/g, '""');
    if (clean.includes(',') || clean.includes('\n') || clean.includes('"')) {
      return `"${clean}"`;
    }
    return clean;
  }
}
