import { ReportDocument } from './ReportModels';
import { ReportExporter } from './ReportExporter';

export class ExcelExporter implements ReportExporter {
  export(document: ReportDocument): Blob {
    let xml = `<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:html="http://www.w3.org/TR/REC-html40">
 <DocumentProperties xmlns="urn:schemas-microsoft-com:office:office">
  <Title>${this.escapeXML(document.title)}</Title>
  <Created>${new Date().toISOString()}</Created>
 </DocumentProperties>
 <Styles>
  <Style ss:ID="Default" ss:Name="Normal">
   <Alignment ss:Vertical="Bottom"/>
   <Borders/>
   <Font ss:FontName="Calibri" x:Family="Swiss" ss:Size="11" ss:Color="#000000"/>
   <Interior/>
   <NumberFormat/>
   <Protection/>
  </Style>
  <Style ss:ID="Header">
   <Font ss:FontName="Calibri" x:Family="Swiss" ss:Size="14" ss:Bold="1" ss:Color="#1f2937"/>
   <Interior ss:Color="#e5e7eb" ss:Pattern="Solid"/>
  </Style>
  <Style ss:ID="TableHeader">
   <Font ss:FontName="Calibri" x:Family="Swiss" ss:Size="11" ss:Bold="1" ss:Color="#ffffff"/>
   <Interior ss:Color="#4f46e5" ss:Pattern="Solid"/>
   <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
  </Style>
  <Style ss:ID="SubHeader">
   <Font ss:FontName="Calibri" x:Family="Swiss" ss:Size="12" ss:Bold="1" ss:Color="#374151"/>
   <Interior ss:Color="#f3f4f6" ss:Pattern="Solid"/>
  </Style>
  <Style ss:ID="CurrencyCell">
   <NumberFormat ss:Format="&quot;₹&quot;#,##0.00;[Red]\(&quot;₹&quot;#,##0.00\);&quot;₹&quot;0.00"/>
  </Style>
  <Style ss:ID="PercentCell">
   <NumberFormat ss:Format="0.0%"/>
  </Style>
 </Styles>
`;

    // Tab 1: Overview
    xml += ` <Worksheet ss:Name="Overview">
  <Table ss:ExpandedColumnCount="5" ss:ExpandedRowCount="18" x:FullColumns="1" x:FullRows="1" ss:DefaultRowHeight="15">
   <Column ss:Width="160"/>
   <Column ss:Width="280"/>
   <Row ss:Height="22">
    <Cell ss:StyleID="Header"><Data ss:Type="String">Report Overview</Data></Cell>
    <Cell ss:StyleID="Header"><Data ss:Type="String">${this.escapeXML(document.title)}</Data></Cell>
   </Row>
   <Row><Cell><Data ss:Type="String">Report ID</Data></Cell><Cell><Data ss:Type="String">${document.id}</Data></Cell></Row>
   <Row><Cell><Data ss:Type="String">Generated At</Data></Cell><Cell><Data ss:Type="String">${document.metadata.generatedAt}</Data></Cell></Row>
   <Row><Cell><Data ss:Type="String">Generated By</Data></Cell><Cell><Data ss:Type="String">${document.metadata.generatedBy}</Data></Cell></Row>
   <Row><Cell><Data ss:Type="String">Integrity Audit Hash</Data></Cell><Cell><Data ss:Type="String">${document.metadata.integrityHash}</Data></Cell></Row>
   <Row><Cell><Data ss:Type="String">Audit Checksum Algorithm</Data></Cell><Cell><Data ss:Type="String">FNV-1a-32bit-custom</Data></Cell></Row>
   <Row><Cell><Data ss:Type="String">AI Integration</Data></Cell><Cell><Data ss:Type="String">${document.metadata.aiEnabled ? 'Enabled' : 'Disabled'}</Data></Cell></Row>
   <Row ss:Height="10"/>
   <Row ss:Height="18">
    <Cell ss:StyleID="SubHeader"><Data ss:Type="String">KPI Metric</Data></Cell>
    <Cell ss:StyleID="SubHeader"><Data ss:Type="String">Value</Data></Cell>
   </Row>
   <Row>
    <Cell><Data ss:Type="String">Total Monthly Inflow</Data></Cell>
    <Cell ss:StyleID="CurrencyCell"><Data ss:Type="Number">${document.kpis.totalIncome}</Data></Cell>
   </Row>
   <Row>
    <Cell><Data ss:Type="String">Total Monthly Outflow</Data></Cell>
    <Cell ss:StyleID="CurrencyCell"><Data ss:Type="Number">${document.kpis.totalExpenses}</Data></Cell>
   </Row>
   <Row>
    <Cell><Data ss:Type="String">Net Inward Surplus</Data></Cell>
    <Cell ss:StyleID="CurrencyCell"><Data ss:Type="Number">${document.kpis.netBalance}</Data></Cell>
   </Row>
   <Row>
    <Cell><Data ss:Type="String">Monthly Savings Rate</Data></Cell>
    <Cell><Data ss:Type="String">${document.kpis.savingsRate}%</Data></Cell>
   </Row>
   <Row>
    <Cell><Data ss:Type="String">Financial Health Score</Data></Cell>
    <Cell><Data ss:Type="Number">${document.kpis.healthScore}</Data></Cell>
   </Row>
   <Row>
    <Cell><Data ss:Type="String">Emergency Runway (Months)</Data></Cell>
    <Cell><Data ss:Type="Number">${document.kpis.runway}</Data></Cell>
   </Row>
  </Table>
 </Worksheet>
`;

    // Tab 2: Cash Flow
    const cashFlowSection = document.sections.find(s => s.id === 'cashflow');
    const cashFlowData = Array.isArray(cashFlowSection?.charts?.[0]?.data) ? cashFlowSection.charts[0].data : [];
    xml += ` <Worksheet ss:Name="Cash Flow">
  <Table ss:ExpandedColumnCount="4" ss:ExpandedRowCount="${cashFlowData.length + 3}" x:FullColumns="1" x:FullRows="1">
   <Column ss:Width="100"/>
   <Column ss:Width="120"/>
   <Column ss:Width="120"/>
   <Column ss:Width="120"/>
   <Row ss:Height="20">
    <Cell ss:StyleID="TableHeader"><Data ss:Type="String">Month</Data></Cell>
    <Cell ss:StyleID="TableHeader"><Data ss:Type="String">Inflow (Income)</Data></Cell>
    <Cell ss:StyleID="TableHeader"><Data ss:Type="String">Outflow (Expense)</Data></Cell>
    <Cell ss:StyleID="TableHeader"><Data ss:Type="String">Net Flow</Data></Cell>
   </Row>
`;
    for (const row of cashFlowData) {
      xml += `   <Row>
    <Cell><Data ss:Type="String">${row.month || ''}</Data></Cell>
    <Cell ss:StyleID="CurrencyCell"><Data ss:Type="Number">${row.income || 0}</Data></Cell>
    <Cell ss:StyleID="CurrencyCell"><Data ss:Type="Number">${row.expense || 0}</Data></Cell>
    <Cell ss:StyleID="CurrencyCell"><Data ss:Type="Number">${row.net || 0}</Data></Cell>
   </Row>
`;
    }
    xml += `  </Table>
 </Worksheet>
`;

    // Tab 3: Budgets
    const budgetsSection = document.sections.find(s => s.id === 'budgets');
    const budgetsData = Array.isArray(budgetsSection?.charts?.[0]?.data) ? budgetsSection.charts[0].data : [];
    xml += ` <Worksheet ss:Name="Budgets">
  <Table ss:ExpandedColumnCount="4" ss:ExpandedRowCount="${budgetsData.length + 3}" x:FullColumns="1" x:FullRows="1">
   <Column ss:Width="150"/>
   <Column ss:Width="120"/>
   <Column ss:Width="120"/>
   <Column ss:Width="100"/>
   <Row ss:Height="20">
    <Cell ss:StyleID="TableHeader"><Data ss:Type="String">Budget Category</Data></Cell>
    <Cell ss:StyleID="TableHeader"><Data ss:Type="String">Amount Spent</Data></Cell>
    <Cell ss:StyleID="TableHeader"><Data ss:Type="String">Budget Limit</Data></Cell>
    <Cell ss:StyleID="TableHeader"><Data ss:Type="String">Utilization %</Data></Cell>
   </Row>
`;
    for (const row of budgetsData) {
      xml += `   <Row>
    <Cell><Data ss:Type="String">${this.escapeXML(row.name || '')}</Data></Cell>
    <Cell ss:StyleID="CurrencyCell"><Data ss:Type="Number">${row.spent || 0}</Data></Cell>
    <Cell ss:StyleID="CurrencyCell"><Data ss:Type="Number">${row.limit || 0}</Data></Cell>
    <Cell><Data ss:Type="String">${row.pct || 0}%</Data></Cell>
   </Row>
`;
    }
    xml += `  </Table>
 </Worksheet>
`;

    // Tab 4: Goals
    const goalsSection = document.sections.find(s => s.id === 'goals');
    const goalsData = Array.isArray(goalsSection?.charts?.[0]?.data) ? goalsSection.charts[0].data : [];
    xml += ` <Worksheet ss:Name="Savings Goals">
  <Table ss:ExpandedColumnCount="4" ss:ExpandedRowCount="${goalsData.length + 3}" x:FullColumns="1" x:FullRows="1">
   <Column ss:Width="180"/>
   <Column ss:Width="120"/>
   <Column ss:Width="120"/>
   <Column ss:Width="100"/>
   <Row ss:Height="20">
    <Cell ss:StyleID="TableHeader"><Data ss:Type="String">Goal Target</Data></Cell>
    <Cell ss:StyleID="TableHeader"><Data ss:Type="String">Current Saved</Data></Cell>
    <Cell ss:StyleID="TableHeader"><Data ss:Type="String">Target Goal Value</Data></Cell>
    <Cell ss:StyleID="TableHeader"><Data ss:Type="String">Completion %</Data></Cell>
   </Row>
`;
    for (const row of goalsData) {
      xml += `   <Row>
    <Cell><Data ss:Type="String">${this.escapeXML(row.name || '')}</Data></Cell>
    <Cell ss:StyleID="CurrencyCell"><Data ss:Type="Number">${row.current || 0}</Data></Cell>
    <Cell ss:StyleID="CurrencyCell"><Data ss:Type="Number">${row.target || 0}</Data></Cell>
    <Cell><Data ss:Type="String">${row.pct || 0}%</Data></Cell>
   </Row>
`;
    }
    xml += `  </Table>
 </Worksheet>
`;

    xml += `</Workbook>`;

    return new Blob([xml], { type: 'application/vnd.ms-excel;charset=utf-8;' });
  }

  private escapeXML(val: string): string {
    if (!val) return '';
    return val
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&apos;');
  }
}
