import { ReportDocument } from './ReportModels';
import { ReportExporter } from './ReportExporter';

export class MarkdownExporter implements ReportExporter {
  export(document: ReportDocument): Blob {
    let md = '';

    md += `# ${document.title}\n\n`;
    
    // Metadata block
    md += `## Report Metadata\n`;
    md += `- **Report ID:** \`${document.id}\`\n`;
    md += `- **Generated At:** ${new Date(document.metadata.generatedAt).toLocaleString()}\n`;
    md += `- **Generated By:** ${document.metadata.generatedBy}\n`;
    md += `- **Period:** \`${document.metadata.period.toUpperCase()}\` (${new Date(document.metadata.startDate).toLocaleDateString()} - ${new Date(document.metadata.endDate).toLocaleDateString()})\n`;
    md += `- **Integrity Audit Hash:** \`${document.metadata.integrityHash}\`\n`;
    md += `- **AI Verification:** ${document.metadata.aiEnabled ? 'Enabled (Aura AI)' : 'Disabled'}\n\n`;

    // Executive Summary
    md += `## Executive Summary\n`;
    md += `> **Headline:** ${document.executive.headline}\n>\n`;
    md += `> ${document.executive.overview}\n\n`;

    if (document.executive.achievements.length > 0) {
      md += `### Key Achievements\n`;
      for (const ach of document.executive.achievements) {
        md += `- ✅ ${ach}\n`;
      }
      md += `\n`;
    }

    if (document.executive.risks.length > 0) {
      md += `### Risks & Vulnerabilities\n`;
      for (const risk of document.executive.risks) {
        md += `- ⚠️ ${risk}\n`;
      }
      md += `\n`;
    }

    if (document.executive.opportunities.length > 0) {
      md += `### Strategic Opportunities\n`;
      for (const opp of document.executive.opportunities) {
        md += `- 💡 ${opp}\n`;
      }
      md += `\n`;
    }

    if (document.executive.recommendations.length > 0) {
      md += `### AI Recommendations\n`;
      for (const rec of document.executive.recommendations) {
        md += `- ➔ ${rec}\n`;
      }
      md += `\n`;
    }

    // KPIs Table
    md += `## Financial Key Performance Indicators (KPIs)\n\n`;
    md += `| KPI Metric | Value |\n`;
    md += `| :--- | :--- |\n`;
    md += `| **Total Inflow (Income)** | ₹${document.kpis.totalIncome.toLocaleString()} |\n`;
    md += `| **Total Outflow (Expenses)** | ₹${document.kpis.totalExpenses.toLocaleString()} |\n`;
    md += `| **Net Surplus / Balance** | ₹${document.kpis.netBalance.toLocaleString()} |\n`;
    md += `| **Monthly Savings Rate** | ${document.kpis.savingsRate}% |\n`;
    md += `| **Overall Financial Health Score** | ${document.kpis.healthScore}/100 |\n`;
    md += `| **Liquidity Fund Runway** | ${document.kpis.runway.toFixed(1)} months |\n\n`;

    // Comparison details if present
    if (document.comparison) {
      md += `## Period Comparison (vs. \`${document.comparison.baseReportTitle}\`)\n\n`;
      md += `| Metric | Base Value | Current Value | Delta | Change Pct | Trend |\n`;
      md += `| :--- | :---: | :---: | :---: | :---: | :---: |\n`;
      
      for (const [key, delta] of Object.entries(document.comparison.kpiDeltas)) {
        const trendIcon = delta.direction === 'up' ? '▲' : delta.direction === 'down' ? '▼' : '▬';
        md += `| **${key}** | ${delta.baseValue.toLocaleString()} | ${delta.currentValue.toLocaleString()} | ${delta.changeAmount.toLocaleString()} | ${delta.changePct}% | ${trendIcon} |\n`;
      }
      md += `\n`;

      if (document.comparison.recommendationsAdded.length > 0) {
        md += `### New Recommendations Appended\n`;
        for (const r of document.comparison.recommendationsAdded) {
          md += `- \`[NEW]\` ${r}\n`;
        }
        md += `\n`;
      }
    }

    // Sections
    md += `## Detailed Report Sections\n\n`;
    for (const section of document.sections) {
      md += `### Section: ${section.title}\n`;
      md += `*${section.summary}*\n\n`;

      // Section specific table formatting
      if (section.id === 'cashflow' && section.charts && section.charts[0]) {
        md += `| Month | Inflow | Outflow | Net Flow |\n`;
        md += `| :--- | :---: | :---: | :---: |\n`;
        const list = Array.isArray(section.charts[0].data) ? section.charts[0].data : [];
        for (const row of list) {
          md += `| ${row.month} | ₹${row.income.toLocaleString()} | ₹${row.expense.toLocaleString()} | ₹${row.net.toLocaleString()} |\n`;
        }
      } else if (section.id === 'budgets' && section.charts && section.charts[0]) {
        md += `| Category | Budget Limit | Amount Spent | Utilization % |\n`;
        md += `| :--- | :---: | :---: | :---: |\n`;
        const list = Array.isArray(section.charts[0].data) ? section.charts[0].data : [];
        for (const row of list) {
          md += `| ${row.name} | ₹${row.limit.toLocaleString()} | ₹${row.spent.toLocaleString()} | ${row.pct}% |\n`;
        }
      } else if (section.id === 'goals' && section.charts && section.charts[0]) {
        md += `| Goal Target | Current Saved | Goal Value | Progress % |\n`;
        md += `| :--- | :---: | :---: | :---: |\n`;
        const list = Array.isArray(section.charts[0].data) ? section.charts[0].data : [];
        for (const row of list) {
          md += `| ${row.name} | ₹${row.current.toLocaleString()} | ₹${row.target.toLocaleString()} | ${row.pct}% |\n`;
        }
      } else {
        // Plain key-value output
        md += `| Parameter | Value |\n`;
        md += `| :--- | :--- |\n`;
        for (const [k, v] of Object.entries(section.data || {})) {
          md += `| ${k} | ${v} |\n`;
        }
      }

      md += `\n`;

      if (section.warnings.length > 0) {
        md += `#### Section Alerts\n`;
        for (const w of section.warnings) {
          md += `- ⚠️ *${w}*\n`;
        }
        md += `\n`;
      }
      md += `---\n\n`;
    }

    md += `\n*Aura Finance Secure Audit Ledger — FNV-1a Checksum Signed*`;

    return new Blob([md], { type: 'text/markdown;charset=utf-8;' });
  }
}
