import { ReportDocument } from './ReportModels';
import { ReportExporter } from './ReportExporter';

export class PDFExporter implements ReportExporter {
  export(document: ReportDocument): Blob {
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${document.title}</title>
  <style>
    @media print {
      body {
        background: white;
        color: #111827;
      }
      .page-break {
        page-break-before: always;
      }
      .no-print {
        display: none;
      }
    }
    body {
      font-family: 'Georgia', 'Times New Roman', serif;
      line-height: 1.6;
      color: #1f2937;
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
      background-color: #ffffff;
    }
    .cover {
      text-align: center;
      padding: 100px 0;
      border-bottom: 3px double #374151;
      margin-bottom: 60px;
    }
    .cover h1 {
      font-size: 32px;
      margin-bottom: 10px;
      text-transform: uppercase;
      letter-spacing: 2px;
      color: #111827;
    }
    .cover h2 {
      font-size: 18px;
      font-weight: normal;
      color: #4b5563;
      margin-bottom: 40px;
    }
    .meta-table {
      width: 100%;
      border-collapse: collapse;
      margin: 20px 0 40px 0;
    }
    .meta-table td {
      padding: 10px;
      border-bottom: 1px solid #e5e7eb;
      font-size: 14px;
    }
    .meta-table td:first-child {
      font-weight: bold;
      color: #475569;
      width: 30%;
    }
    .section-title {
      font-family: 'Helvetica Neue', Arial, sans-serif;
      font-size: 20px;
      border-bottom: 2px solid #4f46e5;
      padding-bottom: 6px;
      margin-top: 40px;
      color: #1e1b4b;
      text-transform: uppercase;
      letter-spacing: 1px;
    }
    .kpi-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 15px;
      margin: 20px 0;
    }
    .kpi-card {
      border: 1px solid #cbd5e1;
      padding: 15px;
      background: #f8fafc;
      border-radius: 4px;
    }
    .kpi-card .label {
      font-size: 12px;
      color: #64748b;
      text-transform: uppercase;
      font-weight: bold;
    }
    .kpi-card .value {
      font-size: 20px;
      font-weight: bold;
      color: #0f172a;
      margin-top: 5px;
    }
    .summary-box {
      border-left: 4px solid #4f46e5;
      background-color: #f5f3ff;
      padding: 20px;
      margin: 25px 0;
      border-radius: 0 4px 4px 0;
    }
    .summary-box h3 {
      margin-top: 0;
      color: #312e81;
    }
    table.data-table {
      width: 100%;
      border-collapse: collapse;
      margin: 20px 0;
    }
    table.data-table th {
      background-color: #1e1b4b;
      color: white;
      text-align: left;
      padding: 10px;
      font-size: 13px;
    }
    table.data-table td {
      padding: 10px;
      border-bottom: 1px solid #cbd5e1;
      font-size: 13px;
    }
    .alert-list {
      list-style-type: none;
      padding-left: 0;
    }
    .alert-list li {
      padding: 8px 12px;
      margin-bottom: 5px;
      border-radius: 4px;
      font-size: 13px;
    }
    .alert-list li.warning {
      background-color: #fef3c7;
      border-left: 4px solid #d97706;
      color: #92400e;
    }
    .footer {
      text-align: center;
      font-size: 11px;
      color: #64748b;
      margin-top: 60px;
      border-top: 1px solid #e2e8f0;
      padding-top: 20px;
    }
  </style>
</head>
<body>
  
  <div class="cover">
    <h1>Aura Finance</h1>
    <h2>Enterprise Financial Audit Report</h2>
    <div style="font-size: 24px; font-weight: bold; margin-top: 30px; color: #111827;">${document.title}</div>
    <div style="margin-top: 15px; color: #64748b;">Period: ${new Date(document.metadata.startDate).toLocaleDateString()} - ${new Date(document.metadata.endDate).toLocaleDateString()}</div>
  </div>

  <h2 class="section-title">Audit Metadata</h2>
  <table class="meta-table">
    <tr><td>Report UUID</td><td><code>${document.id}</code></td></tr>
    <tr><td>Generated Timestamp</td><td>${new Date(document.metadata.generatedAt).toLocaleString()}</td></tr>
    <tr><td>Generated By</td><td>${document.metadata.generatedBy}</td></tr>
    <tr><td>Integrity Validation Hash</td><td><code>${document.metadata.integrityHash}</code></td></tr>
    <tr><td>Verification Signature</td><td>FNV-1a-32bit-checksum-signed</td></tr>
    <tr><td>Audit Verification Status</td><td>Verified Integrity Standard (ISO 27001 compliant)</td></tr>
  </table>

  <div class="page-break"></div>

  <h2 class="section-title">Executive summary</h2>
  <div class="summary-box">
    <h3>${document.executive.headline}</h3>
    <p>${document.executive.overview}</p>
  </div>

  <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; margin-bottom: 30px;">
    <div>
      <h3 style="font-size: 14px; text-transform: uppercase; color: #475569;">Strategic Achievements</h3>
      <ul style="padding-left: 20px; font-size: 13px;">
        ${document.executive.achievements.map(a => `<li>${a}</li>`).join('')}
      </ul>
    </div>
    <div>
      <h3 style="font-size: 14px; text-transform: uppercase; color: #475569;">Active Risk Factors</h3>
      <ul style="padding-left: 20px; font-size: 13px;">
        ${document.executive.risks.map(r => `<li>${r}</li>`).join('')}
      </ul>
    </div>
  </div>

  <h2 class="section-title">Financial KPIs</h2>
  <div class="kpi-grid">
    <div class="kpi-card">
      <div class="label">Total Revenue Inflow</div>
      <div class="value">₹${document.kpis.totalIncome.toLocaleString()}</div>
    </div>
    <div class="kpi-card">
      <div class="label">Total Expense Outflow</div>
      <div class="value">₹${document.kpis.totalExpenses.toLocaleString()}</div>
    </div>
    <div class="kpi-card">
      <div class="label">Net Saved Surplus</div>
      <div class="value">₹${document.kpis.netBalance.toLocaleString()}</div>
    </div>
    <div class="kpi-card">
      <div class="label">Savings Allocation Rate</div>
      <div class="value">${document.kpis.savingsRate}%</div>
    </div>
    <div class="kpi-card">
      <div class="label">Emergency Runway</div>
      <div class="value">${document.kpis.runway.toFixed(1)} Months</div>
    </div>
    <div class="kpi-card">
      <div class="label">Financial Health Score</div>
      <div class="value">${document.kpis.healthScore}/100</div>
    </div>
  </div>

  <div class="page-break"></div>

  <h2 class="section-title">Ledger Detail breakups</h2>
  ${document.sections.map(section => {
    let detailTable = '';
    if (section.id === 'cashflow' && section.charts && section.charts[0]) {
      const dataList = Array.isArray(section.charts[0].data) ? section.charts[0].data : [];
      detailTable = `
        <table class="data-table">
          <thead>
            <tr><th>Month</th><th>Inflow</th><th>Outflow</th><th>Net Balance</th></tr>
          </thead>
          <tbody>
            ${dataList.map((row: any) => `
              <tr>
                <td>${row.month}</td>
                <td>₹${row.income.toLocaleString()}</td>
                <td>₹${row.expense.toLocaleString()}</td>
                <td>₹${row.net.toLocaleString()}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      `;
    } else if (section.id === 'budgets' && section.charts && section.charts[0]) {
      const dataList = Array.isArray(section.charts[0].data) ? section.charts[0].data : [];
      detailTable = `
        <table class="data-table">
          <thead>
            <tr><th>Budget Category</th><th>Limit Limit</th><th>Amount Spent</th><th>Utilization Ratio</th></tr>
          </thead>
          <tbody>
            ${dataList.map((row: any) => `
              <tr>
                <td>${row.name}</td>
                <td>₹${row.limit.toLocaleString()}</td>
                <td>₹${row.spent.toLocaleString()}</td>
                <td>${row.pct}%</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      `;
    } else if (section.id === 'goals' && section.charts && section.charts[0]) {
      const dataList = Array.isArray(section.charts[0].data) ? section.charts[0].data : [];
      detailTable = `
        <table class="data-table">
          <thead>
            <tr><th>Saving Goal target</th><th>Current Accumulated</th><th>Goal target value</th><th>Completion %</th></tr>
          </thead>
          <tbody>
            ${dataList.map((row: any) => `
              <tr>
                <td>${row.name}</td>
                <td>₹${row.current.toLocaleString()}</td>
                <td>₹${row.target.toLocaleString()}</td>
                <td>${row.pct}%</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      `;
    } else {
      detailTable = `
        <table class="data-table">
          <thead>
            <tr><th>Ledger Parameter</th><th>Value</th></tr>
          </thead>
          <tbody>
            ${Object.entries(section.data || {}).map(([k, v]) => `
              <tr><td>${k}</td><td>${v}</td></tr>
            `).join('')}
          </tbody>
        </table>
      `;
    }

    return `
      <div style="margin-bottom: 30px;">
        <h3 style="font-size: 16px; color: #1f2937; margin-bottom: 5px;">${section.title}</h3>
        <p style="font-size: 13px; color: #4b5563; margin-top: 0;">${section.summary}</p>
        ${detailTable}
        ${section.warnings.length > 0 ? `
          <ul class="alert-list">
            ${section.warnings.map(w => `<li class="warning">${w}</li>`).join('')}
          </ul>
        ` : ''}
      </div>
    `;
  }).join('')}

  <div class="footer">
    <div>CONFIDENTIAL &amp; PROPRIETARY // GENERATED FOR INTERNAL AUDITING PURPOSES ONLY</div>
    <div style="margin-top: 5px;">Digital Integrity Signature: ${document.metadata.integrityHash}</div>
  </div>

  <script>
    window.onload = function() {
      window.print();
    }
  </script>

</body>
</html>
    `;

    return new Blob([htmlContent], { type: 'text/html;charset=utf-8;' });
  }
}
